# random seed
seed: 2021


# basic config
do_train: True
model_id: 'test'
model: 'ModernTCN'


# DataLoader
data: 'ETTm1'
root_path: './data/ETT/'
data_path: 'ETTh1.csv'
features: 'M'
target: 'OT'
freq: 'h'
checkpoints: './checkpoints/'
embed: 'timeF'


# forecasting task
seq_len: 96
pred_len: 96



#ModernTCN
stem_ratio: 6
downsample_ratio: 2
ffn_ratio: 2
patch_size: 8
patch_stride: 4
num_blocks: [1]
large_size: [51]
small_size: [5]
dims: [64, 64, 64, 64]
dw_dims: [256, 256, 256, 256]
small_kernel_merged: False
call_structural_reparam: False
use_multi_scale: False


# PatchTST
fc_dropout: 0.05
head_dropout: 0.0
patch_len: 16
stride: 8
padding_patch: 'end'
revin: 1
affine: 0
subtract_last: 0
decomposition: 0
kernel_size: 25
individual: 0


# Formers
embed_type: 0
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1
distil: true
dropout: 0.05
activation: 'gelu'
output_attention: true
do_predict: true


# optimization
num_workers: 10
itr: 1
train_epochs: 100
batch_size: 128
patience: 100
learning_rate: 0.0001
des: test
loss: mse
lradj: type3
pct_start: 0.3
use_amp: false
use_gpu: true
gpu: 0
use_multi_gpu: false
devices: '0,1,2,3'
test_flop: false
