# Basic Config
do_train: True
train_only: False
task_id: test
seed: 2021
model: 'NLinear'

# Data Loader
data: 'ETTm1'
root_path: './data/ETT/'
data_path: 'ETTh1.csv'
features: 'M'
target: 'OT'
freq: 'h'
checkpoints: './checkpoints/'

# Forecasting Task
seq_len: 96
label_len: 48
pred_len: 96

# DLinear
individual: False

# Formers
embed_type: 0
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 1
distil: True
dropout: 0.05
embed: 'timeF'
activation: 'gelu'
output_attention: False
do_predict: False

# Optimization
num_workers: 10
itr: 1
train_epochs: 10
batch_size: 32
patience: 3
learning_rate: 0.0001
des: 'test'
loss: 'mse'
lradj: 'type1'
use_amp: False

# GPU
use_gpu: True
gpu: 0
use_multi_gpu: False
devices: '0,1,2,3'
test_flop: False
